/**
 * Bulk-seed featured drives from the curated KML files in samples/.
 *
 * Each KML in samples/ becomes a featured drive in Firestore:
 *   - Document/name      → drive title
 *   - Document/description (CDATA HTML) → plain-text description (HTML stripped)
 *   - Folder "Route" LineString coordinates → track GeoJSON in Cloud Storage
 *   - Folder "Start / End" Placemarks       → drive's startLat/lng + endLat/lng
 *   - Folder "Scenic Points" Placemarks     → waypoints subcollection (name + description)
 *
 * The "Waypoints" folder in the KML files is intentionally ignored — those are
 * minor route markers without descriptions; only the named "Scenic Points" carry
 * the prose worth surfacing in the app.
 *
 * Doc IDs are derived from filenames:
 *   01_pacific_coast_highway_big_sur.kml → drives/featured-pacific-coast-highway-big-sur
 *
 * Idempotent: re-running overwrites existing featured-* drives with the same
 * slug, re-uploads the track, and replaces the waypoints subcollection.
 *
 * Usage (from functions/):
 *   gcloud auth application-default login   # one-time
 *   npm run seed:kml
 *   npm run seed:kml -- --only=01_pacific_coast_highway_big_sur   # single file
 *   npm run seed:kml -- --dry-run                                  # parse-only, no writes
 */
import * as admin from "firebase-admin";
import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";
import * as zlib from "zlib";
import { encodeGeohash } from "../src/geohash";

// ── bucket detection (mirrors seedFeatured.ts) ──────────────────────────────
function detectStorageBucket(): string {
  if (process.env.FIREBASE_STORAGE_BUCKET) return process.env.FIREBASE_STORAGE_BUCKET;
  try {
    const gsPath = path.resolve(__dirname, "../../app/google-services.json");
    const data = JSON.parse(fs.readFileSync(gsPath, "utf-8"));
    const fromGs = data?.project_info?.storage_bucket;
    if (typeof fromGs === "string" && fromGs.length > 0) return fromGs;
  } catch (_) { /* fall through */ }
  const proj = process.env.GCLOUD_PROJECT || process.env.GOOGLE_CLOUD_PROJECT;
  if (proj) return `${proj}.appspot.com`;
  throw new Error("Could not detect Storage bucket. Set FIREBASE_STORAGE_BUCKET=<bucket>.");
}

admin.initializeApp({ storageBucket: detectStorageBucket() });
const db = admin.firestore();
const bucket = admin.storage().bucket();

const CURATOR_UID = "senik-featured";
const CURATOR_HANDLE = "senik";
const CURATOR_NAME = "Senik";
const SAMPLES_DIR = path.resolve(__dirname, "../../samples");

// ── KML parsing ────────────────────────────────────────────────────────────
interface ScenicPoint {
  name: string;
  description: string;
  lat: number;
  lng: number;
}

interface ParsedKml {
  title: string;
  description: string;
  trackPoints: Array<[number, number]>;     // [lat, lng]
  startLat: number; startLng: number;
  endLat: number; endLng: number;
  scenicPoints: ScenicPoint[];
}

function matchOne(s: string, re: RegExp): string | null {
  const m = re.exec(s);
  return m ? m[1] : null;
}

/** Decode the small set of HTML entities KML names + descriptions actually use. */
function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

/**
 * Strip HTML to readable plain text. Designed for the curated KML descriptions —
 * preserves bullet structure (<li> → "• "), collapses whitespace, decodes the
 * common entities. Not a general-purpose HTML→text — fine because the input is
 * shape-controlled (every KML in samples/ was generated by the same template).
 */
function htmlToText(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|h[1-6])>/gi, "\n\n")
    .replace(/<\/(li|tr)>/gi, "\n")
    .replace(/<li[^>]*>/gi, "• ")
    .replace(/<td[^>]*>/gi, "\t")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&[a-z]+;/gi, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/** Parse a KML coordinates blob (space-separated "lng,lat,alt" tuples) → [[lat, lng], …]. */
function parseCoordinates(blob: string): Array<[number, number]> {
  const out: Array<[number, number]> = [];
  for (const tuple of blob.trim().split(/\s+/)) {
    if (!tuple) continue;
    const parts = tuple.split(",");
    if (parts.length < 2) continue;
    const lng = Number(parts[0]);
    const lat = Number(parts[1]);
    if (Number.isFinite(lat) && Number.isFinite(lng)) out.push([lat, lng]);
  }
  return out;
}

function parseScenicPoints(folderXml: string): ScenicPoint[] {
  const out: ScenicPoint[] = [];
  // Iterate <Placemark> ... </Placemark> blocks within the Scenic Points folder.
  const placemarkRe = /<Placemark>([\s\S]*?)<\/Placemark>/g;
  let m: RegExpExecArray | null;
  while ((m = placemarkRe.exec(folderXml)) !== null) {
    const body = m[1];
    const name = matchOne(body, /<name>([\s\S]*?)<\/name>/);
    const desc = matchOne(body, /<description><!\[CDATA\[([\s\S]*?)\]\]><\/description>/) ?? "";
    const coords = matchOne(body, /<coordinates>([\s\S]*?)<\/coordinates>/);
    if (!name || !coords) continue;
    const [lat, lng] = parseCoordinates(coords)[0] ?? [NaN, NaN];
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) continue;
    out.push({ name: decodeEntities(name.trim()), description: htmlToText(desc), lat, lng });
  }
  return out;
}

function parseKml(xml: string): ParsedKml {
  // Document/name is the first <name> after <Document>.
  const titleRaw = (matchOne(xml, /<Document>[\s\S]*?<name>([\s\S]*?)<\/name>/) ?? "Untitled").trim();
  const title = decodeEntities(titleRaw);
  const descRaw = matchOne(xml, /<description><!\[CDATA\[([\s\S]*?)\]\]><\/description>/) ?? "";
  const description = htmlToText(descRaw);

  // Route folder's coordinates blob.
  const routeBlock = matchOne(
    xml,
    /<Folder>\s*<name>\s*Route\s*<\/name>[\s\S]*?<coordinates>([\s\S]*?)<\/coordinates>/,
  ) ?? "";
  const trackPoints = parseCoordinates(routeBlock);
  if (trackPoints.length < 2) {
    throw new Error(`route has < 2 points (got ${trackPoints.length})`);
  }

  // Start / End placemarks. Names look like "START: Foo (start)" / "END: Bar (end)".
  const startCoords = matchOne(
    xml,
    /<Placemark>\s*<name>\s*START:[^<]*<\/name>[\s\S]*?<coordinates>([\s\S]*?)<\/coordinates>/,
  );
  const endCoords = matchOne(
    xml,
    /<Placemark>\s*<name>\s*END:[^<]*<\/name>[\s\S]*?<coordinates>([\s\S]*?)<\/coordinates>/,
  );
  // Fall back to first/last track point if the Start/End placemarks aren't present.
  const startPair = startCoords ? parseCoordinates(startCoords)[0] : trackPoints[0];
  const endPair = endCoords ? parseCoordinates(endCoords)[0] : trackPoints[trackPoints.length - 1];

  // Scenic Points folder.
  const scenicFolder = matchOne(
    xml,
    /<Folder>\s*<name>\s*Scenic Points\s*<\/name>([\s\S]*?)<\/Folder>/,
  ) ?? "";
  const scenicPoints = parseScenicPoints(scenicFolder);

  return {
    title,
    description,
    trackPoints,
    startLat: startPair[0], startLng: startPair[1],
    endLat: endPair[0], endLng: endPair[1],
    scenicPoints,
  };
}

// ── geometry helpers ───────────────────────────────────────────────────────
function haversineKm(aLat: number, aLng: number, bLat: number, bLng: number): number {
  const r = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLng = ((bLng - aLng) * Math.PI) / 180;
  const lat1 = (aLat * Math.PI) / 180;
  const lat2 = (bLat * Math.PI) / 180;
  const x = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * r * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x));
}

function totalDistanceKm(points: Array<[number, number]>): number {
  let km = 0;
  for (let i = 1; i < points.length; i++) {
    km += haversineKm(points[i - 1][0], points[i - 1][1], points[i][0], points[i][1]);
  }
  return km;
}

function bbox(points: Array<[number, number]>) {
  let n = -Infinity, s = Infinity, e = -Infinity, w = Infinity;
  for (const [lat, lng] of points) {
    if (lat > n) n = lat;
    if (lat < s) s = lat;
    if (lng > e) e = lng;
    if (lng < w) w = lng;
  }
  return { north: n, south: s, east: e, west: w };
}

// ── slug + filename helpers ────────────────────────────────────────────────
function slugFromFilename(file: string): string {
  // "01_pacific_coast_highway_big_sur.kml" → "pacific-coast-highway-big-sur"
  return file.replace(/\.kml$/i, "").replace(/^\d+_/, "").replace(/_/g, "-");
}

function picsum(seed: string, w = 1200, h = 720): string {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`;
}

// ── upload helpers (track, drive doc, waypoints) ───────────────────────────
function buildGeoJson(points: Array<[number, number]>): string {
  return JSON.stringify({
    type: "FeatureCollection",
    features: [{
      type: "Feature",
      geometry: {
        type: "LineString",
        // GeoJSON coordinate order is [lng, lat, alt?].
        coordinates: points.map(([lat, lng]) => [lng, lat]),
      },
      properties: {
        recordedAt: points.map((_, i) => i * 60_000),
        speed: points.map(() => 0),
        accuracy: points.map(() => 0),
      },
    }],
  });
}

async function uploadTrack(driveId: string, points: Array<[number, number]>) {
  const json = buildGeoJson(points);
  const compressed = zlib.gzipSync(Buffer.from(json, "utf-8"));
  const filePath = `tracks/${driveId}.geojson.gz`;
  const token = crypto.randomUUID();
  const file = bucket.file(filePath);
  await file.save(compressed, {
    contentType: "application/gzip",
    metadata: { metadata: { firebaseStorageDownloadTokens: token } },
  });
  const url =
    `https://firebasestorage.googleapis.com/v0/b/${bucket.name}` +
    `/o/${encodeURIComponent(filePath)}?alt=media&token=${token}`;
  return { url, bytes: compressed.length };
}

async function writeWaypoints(driveId: string, points: ScenicPoint[]) {
  const col = db.collection(`drives/${driveId}/waypoints`);
  // Wipe prior seeded waypoints first so re-runs don't accumulate stale ones.
  const existing = await col.where("authorUid", "==", CURATOR_UID).get();
  for (const d of existing.docs) await d.ref.delete();
  const baseTime = Date.now() - 7 * 24 * 60 * 60 * 1000;
  for (let i = 0; i < points.length; i++) {
    const wp = points[i];
    const id = `${driveId}-wp-${i}`;
    await col.doc(id).set({
      authorUid: CURATOR_UID,
      lat: wp.lat,
      lng: wp.lng,
      recordedAt: baseTime + i * 60 * 1000,
      note: wp.description ? `${wp.name}\n\n${wp.description}` : wp.name,
      photoUrls: [],
      hidden: false,
    });
  }
}

async function ensureCuratorProfile() {
  const ref = db.collection("users").doc(CURATOR_UID);
  const snap = await ref.get();
  if (snap.exists && snap.get("anonHandle") === CURATOR_HANDLE) return;
  await ref.set({
    displayName: CURATOR_NAME,
    avatarUrl: null,
    bio: "Curated featured drives.",
    visibility: "public",
    anonHandle: CURATOR_HANDLE,
    points: 0,
    stats: { drivesPublished: 0, helpfulAnswers: 0 },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }, { merge: true });
}

interface SeedOpts { dryRun: boolean }

async function seedFromKml(file: string, opts: SeedOpts): Promise<void> {
  const slug = slugFromFilename(file);
  const driveId = `featured-${slug}`;
  const xml = fs.readFileSync(path.join(SAMPLES_DIR, file), "utf-8");
  let parsed: ParsedKml;
  try {
    parsed = parseKml(xml);
  } catch (e) {
    console.error(`✗ ${file}: parse failed: ${(e as Error).message}`);
    return;
  }

  const distKm = totalDistanceKm(parsed.trackPoints);
  // ~50 km/h average for scenic-route driving with stops; rounds to 60s grain.
  const durationMin = Math.round((distKm / 50) * 60);
  const box = bbox(parsed.trackPoints);
  const centroidLat = (box.north + box.south) / 2;
  const centroidLng = (box.east + box.west) / 2;

  console.log(
    `  ${file}\n` +
    `    title:        ${parsed.title}\n` +
    `    track:        ${parsed.trackPoints.length} pts · ${distKm.toFixed(1)} km · ~${durationMin} min\n` +
    `    waypoints:    ${parsed.scenicPoints.length} scenic POI(s)\n` +
    `    bbox:         N${box.north.toFixed(3)} S${box.south.toFixed(3)} E${box.east.toFixed(3)} W${box.west.toFixed(3)}`,
  );

  if (opts.dryRun) return;

  const { url: trackUrl, bytes: trackBytes } = await uploadTrack(driveId, parsed.trackPoints);
  const now = Date.now();
  const doc = {
    ownerUid: CURATOR_UID,
    ownerAnonHandle: CURATOR_HANDLE,
    title: parsed.title,
    description: parsed.description,
    visibility: "public",
    status: "published",
    startLat: parsed.startLat, startLng: parsed.startLng,
    endLat: parsed.endLat, endLng: parsed.endLng,
    centroidLat, centroidLng,
    distanceM: Math.round(distKm * 1000),
    durationS: durationMin * 60,
    startedAt: now - 7 * 24 * 60 * 60 * 1000,
    endedAt: now - 7 * 24 * 60 * 60 * 1000 + durationMin * 60 * 1000,
    coverPhotoUrl: picsum(`${driveId}-cover`),
    tags: [],  // tags aren't in KML; could be derived from title later
    vehicleSummary: null,
    geohash: encodeGeohash(centroidLat, centroidLng, 9),
    boundingBox: { north: box.north, south: box.south, east: box.east, west: box.west },
    commentCount: 0,
    commentsEnabled: true,
    trackUrl,
    trackBytes,
    updatedAt: now,
    deletedAt: null,
    version: 1,
  };
  await db.doc(`drives/${driveId}`).set(doc, { merge: true });
  await writeWaypoints(driveId, parsed.scenicPoints);
  console.log(`    ✓ wrote drives/${driveId} (track=${trackBytes}B)`);
}

// ── main ───────────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const onlyArg = args.find((a) => a.startsWith("--only="));
  const only = onlyArg ? onlyArg.substring("--only=".length) : null;

  if (!fs.existsSync(SAMPLES_DIR)) {
    console.error(`samples directory not found: ${SAMPLES_DIR}`);
    process.exit(1);
  }
  const all = fs.readdirSync(SAMPLES_DIR).filter((f) => f.endsWith(".kml")).sort();
  const targets = only
    ? all.filter((f) => f.startsWith(only) || f === `${only}.kml`)
    : all;
  if (targets.length === 0) {
    console.error(`no KML files matched (--only=${only ?? "(none)"})`);
    process.exit(1);
  }

  console.log(`${dryRun ? "DRY RUN: " : ""}seeding ${targets.length} KML drive(s)…\n`);
  if (!dryRun) await ensureCuratorProfile();

  let ok = 0, fail = 0;
  for (const file of targets) {
    try {
      await seedFromKml(file, { dryRun });
      ok++;
    } catch (e) {
      console.error(`✗ ${file}: ${(e as Error).message}`);
      fail++;
    }
  }
  console.log(`\nDone. ${ok} succeeded, ${fail} failed${dryRun ? " (dry run, no writes)" : ""}.`);
  if (!dryRun) {
    console.log("The onDriveWritten Cloud Function will fan out to public_drives_index automatically.");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
